// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectWeb.Data;

namespace ProjectWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ProjectWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nghị định"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Quyết định"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Thông báo"
                        });
                });

            modelBuilder.Entity("ProjectWeb.Models.Record", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dear_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("book_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("document_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("document_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("last_fix")
                        .HasColumnType("int");

                    b.Property<DateTime>("signed_day")
                        .HasColumnType("datetime2");

                    b.Property<string>("tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CategoryId = 1,
                            Content = "Đơn xin thôi việc",
                            Dear_to = "Trưởng phòng nhân sự",
                            Destination = "Phòng nhân sự",
                            Image = "image_1.jpg",
                            book_number = "b-123",
                            document_id = "2204",
                            document_name = "Đơn xin thôi việc",
                            last_fix = 15,
                            signed_day = new DateTime(2015, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            version = "#123"
                        },
                        new
                        {
                            id = 2,
                            CategoryId = 2,
                            Content = "Đơn xin nghỉ học",
                            Dear_to = @"Giáo viên chủ nhiệm
Hiệu trưởng",
                            Destination = "Trường đại học Greenwich",
                            Image = "image_2.jpg",
                            book_number = "b-321",
                            document_id = "2205",
                            document_name = "Đơn xin nghỉ học",
                            last_fix = 10,
                            signed_day = new DateTime(2016, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            version = "#321"
                        },
                        new
                        {
                            id = 3,
                            CategoryId = 3,
                            Content = "Đơn xin xác nhận học bổng",
                            Dear_to = @"Chủ tịch tỉnh
Chủ tịch xã
Ban lãnh đạo nhà trường",
                            Destination = @"Ủy ban nhân dân huyện
Trường đại học Greenwich",
                            Image = "image_3.png",
                            book_number = "b-456",
                            document_id = "2206",
                            document_name = "Đơn xin xác nhận học bổng",
                            last_fix = 20,
                            signed_day = new DateTime(2017, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            version = "#456"
                        });
                });

            modelBuilder.Entity("ProjectWeb.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            description1 = "Tờ khai đăng ký kết hôn hiện nay được áp dụng theo quy định tại Thông tư 04/2020/TT-BTP quy định thi hành một số điều của Luật Hộ tịch, có hiệu lực từ ngày 16/7/2020. Theo đó, nếu đi làm thủ tục đăng ký kết hôn, hai người nam nữ phải khai vào tờ khai đăng ký kết hôn để cơ quan có thẩm quyền xác định thông tin nhân thân, nơi cư trú, đã kết hôn mấy lần rồi... Qua đó, làm căn cứ để tiến hành làm thủ tục đăng ký kết hôn cho hai người.",
                            description2 = "",
                            modalId = "m1",
                            name = "kethon",
                            title = "Mẫu đơn đăng ký kết hôn",
                            url = "https://cms.luatvietnam.vn/uploaded/Images/Original/2019/04/11/to-khai-dang-ky-ket-hon-chuan_1104141938.jpg"
                        },
                        new
                        {
                            Id = 2,
                            description1 = "Giấy quyết định ly hôn hay được gọi bằng một tên gọi gần gũi hơn là trích lục ly hôn - là một giấy tờ pháp lý do cơ quan có thẩm quyền ở đây là Tòa án Nhân dân sau khi hoàn thành việc giải quyết ly hôn theo thủ tục ly hôn đơn phương theo quy định pháp luật về tố tụng dân sự và hôn nhân gia dình. Giấy quyết định ly hôn có hiệu lực pháp lý tương đương với bản án quyết định ly hôn của Tòa án. Chính vì vậy, khi xảy ra trường hợp bản án quyết định ly hôn của Tòa án không còn tồn tại thì giấy quyết định ly hôn là một văn bản có hiệu lực pháp lý thay thế.",
                            description2 = "",
                            modalId = "m2",
                            name = "kethon",
                            title = "Mẫu đơn ly hôn",
                            url = "https://cdn.thuvienphapluat.vn/phap-luat/2022/202201/PVQ/thang7/220719/305-1.jpg"
                        },
                        new
                        {
                            Id = 3,
                            description1 = "Bổ nhiệm là việc giao cho một người giữ một chức vụ trong bộ máy nhà nước bằng quyết định của cá nhân hay của cơ quan nhà nước có thẩm quyền. Bổ nhiệm là việc giao cho một người giữ chức vụ trong bộ máy nhà nước bằng quyết định của cá nhân hay của cơ quan nhà nước có thẩm quyền. Bổ nhiệm là việc làm mang tính chất quyền lực nhà nước của người giữ chức vụ nhất định để góp phần kiện toàn và củng cố bộ máy nhà nước, đảm bảo cho bộ máy nhà nước hoạt động có hiệu quả và hiệu lực trên thực tế.",
                            description2 = "",
                            modalId = "m3",
                            name = "quyen",
                            title = "Quyết định bổ nhiệm",
                            url = "https://sanketoan.vn/public/library_staff/25094/images/tailieu2/5(16).PNG"
                        },
                        new
                        {
                            Id = 4,
                            description1 = "Mẫu phiếu đề xuất bổ nhiệm cán bộ là mẫu phiếu được gửi tới cơ quan có thẩm quyền để xem xét bổ nhiệm cán bộ. Mẫu phiếu bổ nhiệm cán bộ được nêu rõ thông tin cá nhân của người được bổ nhiệm, lý do bổ nhiệm, ý kiến của phòng nhân sự, ý kiến của ban giám đốc về việc bổ nhiệm cán bộ mới. ",
                            description2 = "",
                            modalId = "m4",
                            name = "quyen",
                            title = "Đề xuất bổ nhiệm nhân sự",
                            url = "http://1001vieclam.com/bieu-mau-nhan-su/wp-content/uploads/2017/08/de-xuat-bo-nhiem-nhan-su-1.jpg"
                        },
                        new
                        {
                            Id = 5,
                            description1 = "Hợp đồng mua bán nhà ở là sự thoả thuận bằng văn bản giữa bên mua và bên bán, theo đó bên bán có nghĩa vụ chuyển giao nhà ở và quyền sở hữu nhà ở cho bên mua. Bên mua có nghĩa vụ trả tiền cho bên bán đúng thời hạn, địa điểm theo phương thức mà các bên đã thoả thuận trong hợp đồng mua bán nhà ở.",
                            description2 = "Đối tượng của hợp đồng mua bán nhà ở là ngôi nhà hoặc diện tích nhà dùng vào việc ở, sinh hoạt hàng ngày của con người. Nhà ở khác với nhà dùng vào mục đích khác như làm văn phòng, trụ sở cơ quan, kho chứa, cửa hàng, cửa hiệu… Nhưng, khi mua bán nhà ở để dùng vào mục đích khác cũng phải tuân theo các quy định của pháp luật về mua bán nhà ở.",
                            modalId = "m5",
                            name = "dat",
                            title = "Hợp đồng mua bán nhà ở và chuyển đổi quyền sử dung đất",
                            url = "https://sudospaces.com/ketoanleanh/2020/10/hop-dong-mua-ban-nha-o.jpg"
                        },
                        new
                        {
                            Id = 6,
                            description1 = @"Theo pháp luật hiện hành, đơn khiếu nại lấn chiếm không gian là loại văn bản được người khiếu nại dùng để khiếu nại về việc lấn chiếm không gian phát sinh khi khoảng không gian nằm trong diện tích đất của mình bị lấn chiếm bất hợp pháp.

Trên thực tế, việc khiếu nại tranh chấp lối đi chung là một trong những trường hợp phổ biến xảy ra nhất.",
                            description2 = "",
                            modalId = "m6",
                            name = "dat",
                            title = "Đơn khiếu nại lấn chiếm đất",
                            url = "https://o.vdoc.vn/data/image/2022/06/09/don-khieu-nai-giai-quyet-tranh-chap-dat-dai-1.jpg"
                        },
                        new
                        {
                            Id = 7,
                            description1 = @"Theo pháp luật hiện hành, đơn khiếu nại lấn chiếm không gian là loại văn bản được người khiếu nại dùng để khiếu nại về việc lấn chiếm không gian phát sinh khi khoảng không gian nằm trong diện tích đất của mình bị lấn chiếm bất hợp pháp.

Trên thực tế, việc khiếu nại tranh chấp lối đi chung là một trong những trường hợp phổ biến xảy ra nhất.",
                            description2 = "",
                            modalId = "m7",
                            name = "dat",
                            title = "Đơn khiếu nại lấn chiếm đất",
                            url = "https://o.vdoc.vn/data/image/2022/06/09/don-khieu-nai-giai-quyet-tranh-chap-dat-dai-1.jpg"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectWeb.Models.Record", b =>
                {
                    b.HasOne("ProjectWeb.Models.Category", "Category")
                        .WithMany("Records")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
